server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8099/eureka/

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: social-service
          uri: lb://social-service
          filters:
            - StripPrefix=2
          predicates:
            - Path=/api/fs/**
#El predicate es la nueva ruta que toma , la ruta general, pero se respetan las rutas dentro del propio microservicio
#El uri es lb://id-del-servicio
