
#Application Configuration
server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always

# To See H2 Console in Browser:
# http://localhost:8091/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    #url: jdbc:mysql://database-1.czartav11eck.us-east-1.rds.amazonaws.com
    url: jdbc:postgresql://localhost:5432/pruebaDB
    #driverClassName: com.mysql.cj.jdbc.Driver
    driverClassName: org.postgresql.Driver
    ##platform: org.hibernate.dialect.MySQL8Dialect
    platform: org.hibernate.dialect.PostgreSQLDialect
    #username: admin
    username: postgres
    #password: prueba123
    password: Kingjinx18

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry-service:8099/eureka/

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
